### ISSUE TITLE
Consider using the same initial point position for different algorithms

### ISSUE THREAD

**Issue by henryalps** [nengwp/Lion-vs-Adam#2]
Great job on your project! I noticed that each algorithm in your implementation has a different initial point position. Have you considered using the same initial point position for each algorithm?
This would help provide a fair comparison of their performance, especially when testing on the same dataset. Here's a graph to help illustrate my point:

![demo-path](https://github.com/lilipads/gradient_descent_viz/raw/master/resources/screenshots/demo-path.gif)

**Comment by nengwp** [comment]
@henryalps 
Thanks for the insight, it makes sense!
In fact, I tried different optimization algorithms using the same starting point. Their performance is similar to conclusions using different starting points, but many pairs of starting points need to be observed. Randomly different starting points in this implementation happen to observe their own unique characteristics (especially the Lion optimizer), so I keep the characteristic examples.
In contrast, you can change my code to achieve the same starting point, it's very simple.
